name: $name
version: $version
main: io.github.lumine1909.PaperBoatUtils
api-version: $apiVersion
description: $description
authors:
  - Lumine1909
commands:
  spawnboat:
permissions:
  boatutils.admin:
    default: op
  boatutils.boat:
    default: true